title: "BattleshiPPS"
description: An implementation of the battleship game.
remote_theme: just-the-docs/just-the-docs@v0.10.0
search_enabled: true
color_scheme: light
nav_enabled: true

nav_external_links:
  - title: Repository on GitHub
    url: https://github.com/fairlycodeparents/PPS-24-BattleshiPPS

mermaid:
  version: "9.1.3"