name: Build and Test
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        java-version: [ 17, 21 ]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ matrix.java-version }}-${{ matrix.java-distribution }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'sbt'
      - name: Install SBT on macOS
        if: runner.os == 'macOS'
        run: brew install sbt
      - name: Run tests
        run: sbt test

  check-code-formatting:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check scalafmt format
        run: sbt scalafmtCheckAll