name: Validate commit
on:
  pull_request:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: check-conventional-commits
        uses: webiny/action-conventional-commits@v1.3.0